# Generated by Django 5.2 on 2025-04-29 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_info_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CensorInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.CharField(max_length=25)),
                ("certified_by", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="movie_info",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AddField(
            model_name="movie_info",
            name="censor_details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.censorinfo",
            ),
        ),
    ]
